Feature branch
meronokbay/nyt-clone pull request #1
Opened 2020-08-26 09:41 UTC by meronokbay

Clone of an article from the New York Times

2020-08-26 13:49 UTC, bertil291utn commented
# **Status:** Invalid 🚫

## Hey guys I hope you're having a great time

I see all your effort work on this project however I have to invalid due to: 
- [ ] Add a strong description on you README file
- [ ] Edit pull request message
### Summary
-Edit your pull request message, Follow this [guideline](https://cdn.filestackcontent.com/osvFJEkQHWQsgDe0PJoQ)
- Edit README file according to this [guideline](https://github.com/microverseinc/readme-template)

**Note:** to achieve all this check the link that is above this 
<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-08-26 17:24 UTC, SafaErden requested changes
## Status: Require changes ♻️

**Hi TEAM, your project is awesome and it really looks exactly like the original. 👐 However, we need a little fix before we can proceed. Kindly find comments below ⤵**
##

**REQUIRED CHANGES**

Please kindly check and fix the requirements attached below.

##

**SUMMARY**

✨ As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

##

*Kindly make the changes and submit another code review once you are ready💪*


Questions or comments? Reach me on [Twitter](https://twitter.com/safaerden) or [LinkedIn](https://www.linkedin.com/in/safaerden/) 🗨️

Happy coding_ 👨‍💻 

**Safa ERDEN**

2020-08-26 17:24 UTC, SafaErden commented on README.md
> +Feel free to check the [issues page](issues/).
- [x] Your issues link is broken. Please fix it and be more careful about the links you implement in your upcoming projects.

Friendly reminder: Remember it's important to have a professional repo so you can increase your job opportunities. Please take a step back and read the lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.

2020-08-26 17:24 UTC, SafaErden commented on index.html
> +          <p>SPACE & COSMOS</p>
- [x] It has a "Hamburger button", a search icon and a link with text on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from Pathwright). So please add link tag for 'Space and Cosmos'

- [x] Also please consider using HTML Entities instead of using '&';

2020-08-26 17:24 UTC, SafaErden commented on index.html
> +        </div>
- [x] The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)). So please kindly fix it.

2020-08-26 17:24 UTC, SafaErden commented on index.html
> +        </div>
- [OPTIONAL] There is a huge gap between these two sections. Please consider your UI to be adaptive to all the screen resolutions. so please kindly fix it to create the same UI  with the original page.

![image](https://user-images.githubusercontent.com/60184961/91332624-2ac7aa00-e7d5-11ea-9f9b-2538120ff12f.png)

Since the responsive design is not a subject of this project, This issue is flagged as optional but please consider your design is not messed up because of different display sizes in your upcoming projects.

2020-08-26 17:24 UTC, SafaErden commented on index.html
> +      </aside>
- [OPTIONAL] The Editor's pick section merges into the main content, please kindly fix it.
![image](https://user-images.githubusercontent.com/60184961/91333151-e2f55280-e7d5-11ea-916d-e006f4015c1e.png)

Since the responsive design is not a subject of this project, This issue is flagged as optional but please consider your design is not messed up because of different display sizes in your upcoming projects.

2020-08-27 08:18 UTC, Yors-git commented on index.html
> +          <p>SPACE & COSMOS</p>
fixed

2020-08-27 08:18 UTC, Yors-git commented on index.html
> +        </div>
Fixed

2020-08-27 08:36 UTC, Yors-git commented on index.html
> +        </div>
Adjusted

2020-08-27 09:42 UTC, peterrobert approved these changes
### APPROVED :+1: 

Very nice work on this project you have done a great job. Great work on making the changes as requested.

On to the next project

**HAPPY CODING**

2020-08-27 12:12 UTC, merged